tap "denisidoro/tools"
tap "dustinwilson/tap"
tap "federico-terzi/espanso"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-fonts"
tap "homebrew/core"
tap "homebrew/services"
tap "koekeishiya/formulae"
tap "mananapr/cfiles"
tap "mas-cli/tap"
tap "mongodb/brew"
tap "neovim/neovim"
tap "universal-ctags/universal-ctags"
brew "gdbm"
brew "sqlite"
brew "python"
brew "asciinema"
brew "awscli"
brew "fontconfig"
brew "coreutils"
brew "dust"
brew "exa"
brew "exercism"
brew "fd"
brew "libevent"
brew "icu4c"
brew "ffmpeg"
brew "fish"
brew "fzf"
brew "geoip"
brew "git"
brew "git-lfs"
brew "git-now"
brew "gnupg"
brew "gpgme"
brew "gopass"
brew "htop"
brew "hub"
brew "hyperfine"
brew "ifstat"
brew "libtool"
brew "imagemagick"
brew "jq"
brew "kakoune"
brew "khard"
brew "lf"
brew "libuv"
brew "links"
brew "mas"
brew "mdcat"
brew "mpc"
brew "msmtp"
brew "mu"
brew "neofetch"
brew "neovim", args: ["HEAD"]
brew "node"
brew "openvpn"
brew "pandoc"
brew "pass"
brew "pinentry-mac"
brew "python@2"
brew "rename"
brew "ripgrep"
brew "ripmime"
brew "rtv"
brew "rust"
brew "speedtest-cli"
brew "starship"
brew "syncthing"
brew "terminal-notifier"
brew "tig"
brew "tldr"
brew "todo-txt"
brew "trash"
brew "vcprompt"
brew "vim"
brew "wget"
brew "wifi-password"
brew "yarn"
brew "youtube-dl"
brew "z"
brew "zola"
brew "federico-terzi/espanso/espanso"
brew "koekeishiya/formulae/chunkwm", args: ["HEAD"]
brew "koekeishiya/formulae/skhd"
brew "koekeishiya/formulae/yabai"
brew "universal-ctags/universal-ctags/universal-ctags", args: ["HEAD"]
cask "alacritty"
cask "amethyst"
cask "bitwarden"
cask "blender"
cask "chromium"
cask "cinebench"
cask "dozer"
cask "font-cascadia"
cask "font-envy-code-r"
cask "font-fantasque-sans-mono"
cask "font-fontawesome"
cask "font-go-mono"
cask "font-hack"
cask "font-m-plus"
cask "font-sudo"
cask "font-terminus"
cask "geekbench"
cask "gltfquicklook"
cask "glyphs"
cask "godot"
cask "hammerspoon"
cask "iina"
cask "karabiner-elements"
cask "kitty"
cask "mpv"
cask "nativedisplaybrightness"
cask "obs"
cask "protonvpn"
cask "qutebrowser"
cask "slack"
cask "steam"
cask "sublime-text"
cask "syncthing"
cask "tomighty"
cask "ubersicht"
cask "virtualbox"
cask "vlc"
cask "yt-music"
mas "1Blocker", id: 1107421413
mas "1Password 7", id: 1333542190
mas "Agent Intercept", id: 1470156914
mas "Annotate", id: 918207447
mas "Claquette", id: 587748131
mas "Frank DeLoupe", id: 530458789
mas "GIPHY CAPTURE", id: 668208984
mas "iA Writer", id: 775737590
mas "Keep It", id: 1272768911
mas "Keynote", id: 409183694
mas "Lifeslide", id: 1472966601
mas "Markoff", id: 1084713122
mas "Numbers", id: 409203825
mas "Pages", id: 409201541
mas "Soulver", id: 413965349
mas "SwiftoDo Desktop", id: 1143641091
mas "The Unarchiver", id: 425424353
mas "Things", id: 904280696
mas "WiFi Explorer Lite", id: 1408727408
