tap "denisidoro/tools"
tap "dustinwilson/tap"
tap "federico-terzi/espanso"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-drivers"
tap "homebrew/cask-fonts"
tap "homebrew/cask-versions"
tap "homebrew/core"
tap "homebrew/services"
tap "koekeishiya/formulae"
tap "lukakerr/things"
tap "mananapr/cfiles"
tap "mas-cli/tap"
tap "mongodb/brew"
tap "neovim/neovim"
tap "vitorgalvao/tiny-scripts"
brew "gdbm"
brew "sqlite"
brew "asciinema"
brew "awscli"
brew "icu4c"
brew "bitwarden-cli"
brew "fontconfig"
brew "python"
brew "coreutils"
brew "dust"
brew "exa"
brew "exercism"
brew "fd"
brew "libevent"
brew "ffmpeg"
brew "fish"
brew "fzf"
brew "geoip"
brew "git"
brew "git-lfs"
brew "git-now"
brew "gnupg"
brew "gpgme"
brew "gopass"
brew "htop"
brew "hub"
brew "hyperfine"
brew "ifstat"
brew "libtool"
brew "imagemagick"
brew "jq"
brew "kakoune"
brew "lf"
brew "libuv"
brew "links"
brew "mas"
brew "mdcat"
brew "mpc"
brew "msmtp"
brew "mu"
brew "neofetch"
brew "neovim", args: ["HEAD"]
brew "openvpn"
brew "pandoc"
brew "pass"
brew "pinentry-mac"
brew "python@2"
brew "redis"
brew "rename"
brew "ripgrep"
brew "ripmime"
brew "rtv"
brew "rust"
brew "scons"
brew "speedtest-cli"
brew "starship"
brew "syncthing"
brew "terminal-notifier"
brew "tig"
brew "tldr"
brew "tmux"
brew "todo-txt"
brew "trash"
brew "vcprompt"
brew "vim"
brew "vulkan-headers"
brew "w3m"
brew "wget"
brew "yarn"
brew "youtube-dl"
brew "z"
brew "federico-terzi/espanso/espanso"
brew "koekeishiya/formulae/skhd"
brew "koekeishiya/formulae/yabai"
brew "mongodb/brew/mongodb-community@3.6", link: true
brew "vitorgalvao/tiny-scripts/cask-repair"
cask "acorn"
cask "alacritty"
cask "alfred"
cask "appcleaner"
cask "bitwarden"
cask "blender"
cask "cakebrew"
cask "chromium"
cask "coconutbattery"
cask "dejalu"
cask "docker"
cask "dozer"
cask "dropshare"
cask "epic-games"
cask "etrecheckpro"
cask "figma"
cask "firefox"
cask "firefox-developer-edition"
cask "firefox-nightly"
cask "font-cascadia"
cask "font-envy-code-r"
cask "font-fantasque-sans-mono"
cask "font-fontawesome"
cask "font-hack"
cask "font-input"
cask "font-inter"
cask "font-jetbrains-mono"
cask "font-luculent"
cask "font-m-plus"
cask "font-sudo"
cask "fsnotes"
cask "geekbench"
cask "gifox"
cask "github"
cask "gltfquicklook"
cask "godot"
cask "hammerspoon"
cask "iina"
cask "intel-power-gadget"
cask "itch"
cask "iterm2"
cask "itsycal"
cask "kap"
cask "karabiner-elements"
cask "kitty"
cask "latest"
cask "magicavoxel"
cask "mullvadvpn"
cask "nativedisplaybrightness"
cask "netnewswire"
cask "notable"
cask "protonvpn"
cask "quitter"
cask "safari-technology-preview"
cask "scapple"
cask "sf-symbols"
cask "slack"
cask "sloth"
cask "steam"
cask "sublime-merge"
cask "sublime-text"
cask "taskpaper"
cask "telegram"
cask "textmate"
cask "textual"
cask "timemachineeditor"
cask "tomighty"
cask "twine"
cask "ubersicht"
cask "viscosity"
cask "visual-studio-code"
cask "zoomus"
mas "1Blocker", id: 1107421413
mas "Annotate", id: 918207447
mas "app.seashore", id: 1448648921
mas "Blackmagic RAW Speed Test", id: 1466185689
mas "Bumpr", id: 1166066070
mas "Claquette", id: 587748131
mas "Disk Speed Test", id: 425264550
mas "GIF Brewery 3", id: 1081413713
mas "Gifski", id: 1351639930
mas "GoodNotes", id: 1480793815
mas "iA Writer", id: 775737590
mas "iStat Menus", id: 1319778037
mas "Keep It", id: 1272768911
mas "Keynote", id: 409183694
mas "Numbers", id: 409203825
mas "OverPicture", id: 1188020834
mas "Soulver", id: 413965349
mas "SwiftoDo Desktop", id: 1143641091
mas "The Unarchiver", id: 425424353
mas "Things", id: 904280696
mas "Trello", id: 1278508951
mas "WiFi Explorer Lite", id: 1408727408
mas "Wipr", id: 1320666476
mas "WireGuard", id: 1451685025
mas "Xcode", id: 497799835
